import type {
  StudioDesign,
  ExportBundle,
  AgentDefinition,
  SkillDefinition,
  HeartbeatDefinition,
  DeploymentRecommendation,
  StudioGraph,
  StudioNode,
  ValidationResult,
} from '@openclaw-studio/shared';
import { NodeType, EdgeRelationType } from '@openclaw-studio/shared';
import type { AgentNodeConfig, SkillNodeConfig, HeartbeatNodeConfig, ToolNodeConfig, WorkspaceNodeConfig } from '@openclaw-studio/shared';
import { validationService } from './validation.service';

function getConnectedNodes(graph: StudioGraph, nodeId: string, relationType?: EdgeRelationType): StudioNode[] {
  const connectedIds = graph.edges
    .filter((e) => {
      const matches = e.source === nodeId || e.target === nodeId;
      if (!matches) return false;
      if (relationType && e.relation_type !== relationType) return false;
      return true;
    })
    .map((e) => (e.source === nodeId ? e.target : e.source));

  return graph.nodes.filter((n) => connectedIds.includes(n.id));
}

export class ExportService {
  async generateBundle(design: StudioDesign): Promise<ExportBundle> {
    const graph: StudioGraph = design.graph || {
      nodes: [],
      edges: [],
      metadata: { name: design.name, description: design.description, created_at: '', updated_at: '', version: 1 },
    };

    // Run validation (with safe clone)
    let validationReport: ValidationResult;
    try {
      validationReport = await validationService.validate(
        JSON.parse(JSON.stringify(graph)),
      );
    } catch {
      // If validation fails, continue with empty report
      validationReport = { valid: false, errors: [], warnings: [] };
    }

    // Extract agent definitions
    const agentNodes = graph.nodes.filter((n) => n.type === NodeType.Agent);
    const agentDefinitions: AgentDefinition[] = agentNodes.map((agentNode) => {
      const cfg = agentNode.config as AgentNodeConfig;

      // Skills: from agent config + from connected skill nodes
      const edgeSkills = getConnectedNodes(graph, agentNode.id, EdgeRelationType.Invokes)
        .filter((n) => n.type === NodeType.Skill)
        .map((n) => (n.config as SkillNodeConfig).name);
      const configSkills = cfg.skills || [];
      const connectedSkills = [...new Set([...configSkills, ...edgeSkills])];

      // Tools: from agent config + from connected tool nodes
      const edgeTools = getConnectedNodes(graph, agentNode.id, EdgeRelationType.Uses)
        .filter((n) => n.type === NodeType.Tool)
        .map((n) => (n.config as ToolNodeConfig).binding_name);
      const configTools = cfg.tools || [];
      const connectedTools = [...new Set([...configTools, ...edgeTools])];

      // Find connected heartbeat
      const connectedHeartbeats = getConnectedNodes(graph, agentNode.id, EdgeRelationType.ManagedBy)
        .filter((n) => n.type === NodeType.Heartbeat);
      let heartbeatConfig: HeartbeatDefinition | undefined;
      if (connectedHeartbeats.length > 0) {
        const hbCfg = connectedHeartbeats[0].config as HeartbeatNodeConfig;
        heartbeatConfig = {
          mode: hbCfg.mode,
          schedule: hbCfg.schedule,
          purpose: hbCfg.purpose,
          escalation_summary: hbCfg.escalation_summary,
        };
      }

      return {
        name: cfg.name || 'Unnamed Agent',
        role: cfg.role || '',
        goal: cfg.goal || cfg.description || '',
        description: cfg.description || '',
        model: cfg.model || 'claude-sonnet-4-20250514',
        workspace_files: {}, // Generated by the adapter at publish time
        heartbeat_config: heartbeatConfig,
        skills: connectedSkills,
        tools: connectedTools,
        personality: cfg.personality,
        communication_style: cfg.communication_style,
        responsibilities: cfg.responsibilities,
        do_rules: cfg.do_rules,
        dont_rules: cfg.dont_rules,
        handoffs: cfg.handoffs,
        rules: cfg.rules,
        example_interactions: cfg.example_interactions,
        temperature: cfg.temperature,
        timeout_seconds: cfg.timeout_seconds,
        max_tokens: cfg.max_tokens,
        model_fallback: cfg.model_fallback,
        channel_binding: cfg.channel_binding,
        is_default: cfg.is_default,
        sandbox_mode: cfg.sandbox_mode,
        tools_allow: cfg.tools_allow,
        tools_deny: cfg.tools_deny,
      };
    });

    // Extract skill definitions
    const skillNodes = graph.nodes.filter((n) => n.type === NodeType.Skill);
    const skillDefinitions: SkillDefinition[] = skillNodes.map((skillNode) => {
      const cfg = skillNode.config as SkillNodeConfig;
      return {
        name: cfg.name,
        description: cfg.purpose,
        purpose: cfg.purpose,
        prompt_summary: cfg.prompt_summary,
        input_schema: cfg.input_schema,
        output_schema: cfg.output_schema,
      };
    });

    // Extract heartbeat definitions
    const heartbeatNodes = graph.nodes.filter((n) => n.type === NodeType.Heartbeat);
    const heartbeatDefinitions: HeartbeatDefinition[] = heartbeatNodes.map((hbNode) => {
      const cfg = hbNode.config as HeartbeatNodeConfig;
      return {
        mode: cfg.mode,
        schedule: cfg.schedule,
        purpose: cfg.purpose,
        escalation_summary: cfg.escalation_summary,
      };
    });

    // Workspace metadata
    const workspaceNodes = graph.nodes.filter((n) => n.type === NodeType.Workspace);
    const workspaceMetadata: Record<string, unknown> = {};
    for (const wsNode of workspaceNodes) {
      const cfg = wsNode.config as WorkspaceNodeConfig;
      workspaceMetadata[wsNode.id] = {
        label: wsNode.label,
        notes: cfg.notes,
        metadata_summary: cfg.metadata_summary,
        template_ref: cfg.workspace_template_ref,
      };
    }

    // Reusable asset report
    const reusableNodes = graph.nodes.filter((n) => n.reused_asset_ref);
    const reusableAssetReport: Record<string, unknown> = {
      count: reusableNodes.length,
      assets: reusableNodes.map((n) => ({
        node_id: n.id,
        label: n.label,
        type: n.type,
        reused_asset_ref: n.reused_asset_ref,
      })),
    };

    // Proposed new asset report
    const proposedNewNodes = graph.nodes.filter((n) => n.proposed_new);
    const proposedNewAssetReport: Record<string, unknown> = {
      count: proposedNewNodes.length,
      assets: proposedNewNodes.map((n) => ({
        node_id: n.id,
        label: n.label,
        type: n.type,
      })),
    };

    // Design summary markdown
    const designSummaryMd = `# ${design.name}

## Description
${design.description || 'No description provided.'}

## Architecture Overview
- **Agents**: ${agentDefinitions.length}
- **Skills**: ${skillDefinitions.length}
- **Heartbeats**: ${heartbeatDefinitions.length}
- **Total Nodes**: ${graph.nodes.length}
- **Total Edges**: ${graph.edges.length}

## Agents
${agentDefinitions.map((a) => `### ${a.name}\n- **Role**: ${a.role}\n- **Goal**: ${a.goal}\n- **Skills**: ${a.skills.join(', ') || 'None'}\n- **Tools**: ${a.tools.join(', ') || 'None'}`).join('\n\n')}

## Validation
- **Status**: ${validationReport.valid ? 'PASSED' : 'FAILED'}
- **Errors**: ${validationReport.errors.length}
- **Warnings**: ${validationReport.warnings.length}

## Use Case
${design.use_case_prompt || 'No use case prompt provided.'}
`;

    // Deployment recommendation
    const deploymentRecommendation: DeploymentRecommendation = {
      agents: agentDefinitions.map((a) => ({
        agent_name: a.name,
        runtime_requirements: [
          'Node.js 18+',
          ...(a.heartbeat_config ? ['Cron scheduler'] : []),
          ...(a.tools.length > 0 ? ['API credentials for tools'] : []),
        ],
        env_vars: [
          `${a.name.toUpperCase().replace(/\s+/g, '_')}_API_KEY`,
          ...(a.tools.map((t) => `${t.toUpperCase()}_API_KEY`)),
        ],
        notes: `Agent "${a.name}" requires ${a.skills.length} skill(s) and ${a.tools.length} tool(s).`,
      })),
      dependencies: [
        'openclaw-runtime',
        ...(heartbeatDefinitions.length > 0 ? ['cron-scheduler'] : []),
        ...(skillDefinitions.length > 0 ? ['skill-executor'] : []),
      ],
      notes: [
        `Bundle generated for design "${design.name}"`,
        `Contains ${agentDefinitions.length} agent(s), ${skillDefinitions.length} skill(s), ${heartbeatDefinitions.length} heartbeat(s)`,
        validationReport.valid ? 'All validation checks passed' : `Validation found ${validationReport.errors.length} error(s)`,
      ],
    };

    return {
      design_summary_md: designSummaryMd,
      graph,
      reusable_asset_report: reusableAssetReport,
      proposed_new_asset_report: proposedNewAssetReport,
      validation_report: validationReport,
      agent_definitions: agentDefinitions,
      skill_definitions: skillDefinitions,
      heartbeat_definitions: heartbeatDefinitions,
      workspace_metadata: workspaceMetadata,
      deployment_recommendation: deploymentRecommendation,
    };
  }
}

export const exportService = new ExportService();
